# Generated by Django 3.1.1 on 2021-01-16 15:20

import cloudinary.models
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', fernet_fields.fields.EncryptedTextField()),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('date', models.CharField(max_length=20, verbose_name='Data da sessão')),
                ('servico', models.CharField(choices=[], max_length=50, verbose_name='Servico')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinhaInformacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('nomeLugar', models.CharField(max_length=50, verbose_name='Nome do lugar')),
                ('frase', models.CharField(max_length=255, verbose_name='Frase do logo')),
                ('instagram', models.CharField(max_length=50, verbose_name='Nome do usúario Instagram')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto da capa')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto do logo')),
            ],
            options={
                'verbose_name_plural': 'Minhas informações',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemPromo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto da Promoção')),
                ('tituloPromo', models.CharField(max_length=50, verbose_name='Titulo da Promoção')),
                ('descPromo', models.CharField(max_length=255, verbose_name='Descrição com detalhes da promoção')),
                ('dataDuracao', models.DateField(verbose_name='Data final da Promoção')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('choice', models.CharField(choices=[('agenda', 'Agenda Completa'), ('nome', 'nome'), ('telefone', 'telefone'), ('email', 'email'), ('servico', 'servico')], max_length=255, verbose_name='Filtrar por')),
                ('nomePesquisa', models.CharField(max_length=100, verbose_name='Coloque a pesquisa')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50, verbose_name='servico')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('upload', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto do serviço')),
            ],
        ),
    ]
