# Generated by Django 3.1.1 on 2021-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=models.CharField(choices=[('a', 'b'), ('c', 'd')], max_length=50, verbose_name='Servico'),
        ),
    ]
