# Generated by Django 3.1.1 on 2021-01-16 15:44

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210116_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=fernet_fields.fields.EncryptedDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='date',
            field=fernet_fields.fields.EncryptedCharField(max_length=20, verbose_name='Data da sessão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=fernet_fields.fields.EncryptedTextField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=fernet_fields.fields.EncryptedCharField(choices=[('a', 'b'), ('c', 'd')], max_length=50, verbose_name='Servico'),
        ),
    ]
